FROM node:21 as builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm rum build


FROM nginx:alpine
COPY --from=builder /app/dist/my-angular-app/browser usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY mime.types /etc/nginx/mime.types
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

#docker build -t angular-docker .
#docker run -p 8080:80 angular-docker .
