# Use a imagem base do Node.js para construir a aplicação
FROM node:18 AS builder

# Crie um diretório para a aplicação
WORKDIR /app

# Copie o package.json e o package-lock.json (se houver) para o diretório de trabalho
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o código da aplicação para o diretório de trabalho
COPY . .

# Construa a aplicação Angular
RUN npm run build --prod

# Use uma imagem base do Nginx para servir a aplicação
FROM nginx:alpine

# Copie os arquivos construídos para o diretório do Nginx
COPY --from=builder /app/dist/ /usr/share/nginx/html

# Exponha a porta 80
EXPOSE 80

# Inicie o Nginx
CMD ["nginx", "-g", "daemon off;"]


#docker build -t minha-aplicacao-angular .
#docker run -d -p 8080:80 minha-aplicacao-angular
